#!/usr/bin/env python3
"""Build the compact lunar albedo map used by the Canvas renderer.

Requires Pillow (`python3 -m pip install Pillow`). The generated map is a
128×64 equirectangular luminance texture derived from NASA SVS's LRO/WAC
color mosaic. Keeping one byte per texel preserves the actual global maria
and highland pattern for only 8 KiB before bundling.
"""

from __future__ import annotations

import base64
import hashlib
import io
import json
from pathlib import Path
from urllib.request import Request, urlopen

try:
    from PIL import Image
except ImportError as error:  # pragma: no cover - authoring-only utility
    raise SystemExit("Pillow is required: python3 -m pip install Pillow") from error


SOURCE_URL = "https://svs.gsfc.nasa.gov/vis/a000000/a004700/a004720/lroc_color_2k.jpg"
SOURCE_PAGE = "https://svs.gsfc.nasa.gov/4720/"
WIDTH = 128
HEIGHT = 64
ROOT = Path(__file__).resolve().parents[1]
DATA_DIRECTORY = ROOT / "src" / "data"


def sha256(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def main() -> None:
    request = Request(SOURCE_URL, headers={"User-Agent": "CosmicCalendar catalog updater"})
    with urlopen(request, timeout=60) as response:
        source = response.read()

    with Image.open(io.BytesIO(source)) as image:
        resized = image.convert("RGB").resize((WIDTH, HEIGHT), Image.Resampling.LANCZOS)
        # The source mosaic is already photometrically normalized and encoded
        # for display. Preserve its perceptual luminance for browser tone mapping.
        albedo = bytes(
            round(0.2126 * red + 0.7152 * green + 0.0722 * blue)
            for red, green, blue in resized.get_flattened_data()
        )

    encoded = base64.b64encode(albedo).decode("ascii")
    chunks = [encoded[index:index + 96] for index in range(0, len(encoded), 96)]
    module = "\n".join([
        "// Generated by scripts/updateMoonAlbedo.py. Do not edit manually.",
        f"export const MOON_ALBEDO_WIDTH = {WIDTH};",
        f"export const MOON_ALBEDO_HEIGHT = {HEIGHT};",
        "export const MOON_ALBEDO_BASE64 = [",
        *(f"  '{chunk}'," for chunk in chunks),
        "].join('');",
        "",
    ])
    metadata = {
        "source": SOURCE_PAGE,
        "sourceAsset": SOURCE_URL,
        "sourceSha256": sha256(source),
        "projection": "equirectangular, centered on 0 degrees longitude, north up",
        "encoding": "8-bit perceptual luminance, row-major, base64 embedded",
        "width": WIDTH,
        "height": HEIGHT,
        "byteLength": len(albedo),
        "albedoSha256": sha256(albedo),
        "credit": "NASA Scientific Visualization Studio; LRO Camera WAC mosaic",
    }

    DATA_DIRECTORY.mkdir(parents=True, exist_ok=True)
    (DATA_DIRECTORY / "moon-albedo-embedded.ts").write_text(module, encoding="utf-8")
    (DATA_DIRECTORY / "moon-albedo.json").write_text(
        json.dumps(metadata, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
