import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { gunzipSync } from 'node:zlib';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE_URL = 'https://cdsarc.cds.unistra.fr/ftp/V/50/catalog.gz';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dataDirectory = path.join(root, 'src', 'data');
const outputPath = path.join(dataDirectory, 'bright-stars.bin');
const manifestPath = path.join(dataDirectory, 'bright-stars.json');
const embeddedPath = path.join(dataDirectory, 'bright-stars-embedded.ts');
const RECORD_SIZE = 18;
const HEADER_SIZE = 12;
const MISSING_COLOR_INDEX = -32_768;

const field = (line, start, end) => line.slice(start - 1, end).trim();
const numberField = (line, start, end) => {
  const value = field(line, start, end);
  return value ? Number(value) : undefined;
};
const sha256 = (value) => createHash('sha256').update(value).digest('hex');

function parseStar(line) {
  const hr = numberField(line, 1, 4);
  const rightAscensionHours = numberField(line, 76, 77);
  const rightAscensionMinutes = numberField(line, 78, 79);
  const rightAscensionSeconds = numberField(line, 80, 83);
  const declinationDegrees = numberField(line, 85, 86);
  const declinationMinutes = numberField(line, 87, 88);
  const declinationSeconds = numberField(line, 89, 90);
  const visualMagnitude = numberField(line, 103, 107);
  if (
    hr === undefined || rightAscensionHours === undefined ||
    rightAscensionMinutes === undefined || rightAscensionSeconds === undefined ||
    declinationDegrees === undefined || declinationMinutes === undefined ||
    declinationSeconds === undefined || visualMagnitude === undefined
  ) return undefined;

  const declinationSign = field(line, 84, 84) === '-' ? -1 : 1;
  return {
    hr,
    rightAscensionDegrees: (
      rightAscensionHours + rightAscensionMinutes / 60 + rightAscensionSeconds / 3_600
    ) * 15,
    declinationDegrees: declinationSign * (
      declinationDegrees + declinationMinutes / 60 + declinationSeconds / 3_600
    ),
    visualMagnitude,
    colorIndex: numberField(line, 110, 114),
    properMotionRaArcsecondsPerYear: numberField(line, 149, 154) ?? 0,
    properMotionDecArcsecondsPerYear: numberField(line, 155, 160) ?? 0,
  };
}

function encode(stars) {
  const bytes = Buffer.alloc(HEADER_SIZE + stars.length * RECORD_SIZE);
  bytes.write('CCSC', 0, 'ascii');
  bytes.writeUInt16LE(1, 4);
  bytes.writeUInt16LE(stars.length, 6);
  bytes.writeUInt16LE(RECORD_SIZE, 8);
  bytes.writeUInt16LE(0, 10);

  stars.forEach((star, index) => {
    const offset = HEADER_SIZE + index * RECORD_SIZE;
    bytes.writeUInt16LE(star.hr, offset);
    bytes.writeUInt32LE(Math.round(star.rightAscensionDegrees * 10_000), offset + 2);
    bytes.writeInt32LE(Math.round(star.declinationDegrees * 10_000), offset + 6);
    bytes.writeInt16LE(Math.round(star.visualMagnitude * 100), offset + 10);
    bytes.writeInt16LE(
      star.colorIndex === undefined ? MISSING_COLOR_INDEX : Math.round(star.colorIndex * 100),
      offset + 12,
    );
    bytes.writeInt16LE(Math.round(star.properMotionRaArcsecondsPerYear * 1_000), offset + 14);
    bytes.writeInt16LE(Math.round(star.properMotionDecArcsecondsPerYear * 1_000), offset + 16);
  });
  return bytes;
}

const response = await fetch(SOURCE_URL);
if (!response.ok) throw new Error(`Bright Star Catalogue download failed: HTTP ${response.status}`);
const compressed = Buffer.from(await response.arrayBuffer());
const catalog = gunzipSync(compressed).toString('latin1');
const stars = catalog.split(/\r?\n/).map(parseStar).filter(Boolean);
const encoded = encode(stars);

await mkdir(dataDirectory, { recursive: true });
await writeFile(outputPath, encoded);
await writeFile(
  embeddedPath,
  `// Generated by scripts/updateBrightStarCatalog.mjs for lazy-loaded library builds.\nconst encodedCatalog: string = '${encoded.toString('base64')}';\nexport default encodedCatalog;\n`,
);
await writeFile(manifestPath, `${JSON.stringify({
  catalog: 'Bright Star Catalogue, Fifth Revised Edition (V/50)',
  authors: 'Hoffleit and Warren (1991)',
  sourceUrl: SOURCE_URL,
  sourceSha256: sha256(compressed),
  binarySha256: sha256(encoded),
  epoch: 'J2000.0',
  count: stars.length,
  recordSizeBytes: RECORD_SIZE,
  encoding: 'CCSC v1 little-endian',
}, null, 2)}\n`);

console.log(`Wrote ${stars.length} stars to ${path.relative(root, outputPath)} (${encoded.length} bytes).`);
