import { createHash } from 'node:crypto';
import { gunzipSync } from 'node:zlib';
import { writeFile } from 'node:fs/promises';

const SOURCE_URL = 'https://cdsarc.cds.unistra.fr/ftp/J/ApJ/944/94/table4.dat.gz';
const EXPECTED_ROWS = 38_053;
const SLICE_LIMIT = 1_000;
const SAMPLE_COUNT = 1_900;

const response = await fetch(SOURCE_URL);
if (!response.ok) throw new Error(`CF4 download failed: ${response.status} ${response.statusText}`);
const compressed = Buffer.from(await response.arrayBuffer());
const sourceSha256 = createHash('sha256').update(compressed).digest('hex');
const text = gunzipSync(compressed).toString('ascii');

const rows = text.split('\n').filter(Boolean).map((line) => ({
  pgc: Number.parseInt(line.slice(0, 7), 10),
  vpec: Number.parseInt(line.slice(64, 69), 10),
  sgx: Number.parseInt(line.slice(137, 143), 10),
  sgy: Number.parseInt(line.slice(144, 150), 10),
  sgz: Number.parseInt(line.slice(151, 157), 10),
}));
if (rows.length !== EXPECTED_ROWS || rows.some((row) => Object.values(row).some(Number.isNaN))) {
  throw new Error(`Unexpected CF4 table shape: ${rows.length} parsed rows`);
}

const slice = rows.filter(({ sgx, sgy, sgz }) =>
  sgx >= -18_000 && sgx <= 8_000 &&
  sgy >= -8_500 && sgy <= 12_000 &&
  Math.abs(sgz) <= SLICE_LIMIT);
const selected = slice
  .map((row) => ({
    row,
    rank: createHash('sha256').update(`cf4-${row.pgc}`).digest('hex'),
  }))
  .sort((first, second) => first.rank.localeCompare(second.rank))
  .slice(0, SAMPLE_COUNT)
  .map(({ row }) => row)
  .sort((first, second) => first.sgx - second.sgx || first.sgy - second.sgy || first.pgc - second.pgc);
if (selected.length !== SAMPLE_COUNT) throw new Error(`Only ${selected.length} CF4 slice rows selected`);

const packed = Buffer.alloc(selected.length * 8);
selected.forEach((row, index) => {
  const offset = index * 8;
  packed.writeInt16LE(row.sgx, offset);
  packed.writeInt16LE(row.sgy, offset + 2);
  packed.writeInt16LE(row.sgz, offset + 4);
  packed.writeInt16LE(row.vpec, offset + 6);
});

const generatedGroups = `// Generated by scripts/updateCosmicFlowCatalog.mjs from the published Cosmicflows-4 Table 4.\n` +
  `export const CF4_GROUP_PACKED_BASE64: string = '${packed.toString('base64')}';\n`;
const generatedMetadata = `// Generated by scripts/updateCosmicFlowCatalog.mjs.\n` +
  `export const CF4_GROUP_SOURCE_URL = '${SOURCE_URL}';\n` +
  `export const CF4_GROUP_SOURCE_SHA256 = '${sourceSha256}';\n` +
  `export const CF4_GROUP_SOURCE_ROW_COUNT = ${rows.length};\n` +
  `export const CF4_GROUP_SLICE_AVAILABLE_COUNT = ${slice.length};\n` +
  `export const CF4_GROUP_SAMPLE_COUNT = ${selected.length};\n` +
  `export const CF4_GROUP_SLICE_SGZ_LIMIT_VELOCITY_UNITS = ${SLICE_LIMIT};\n`;

await Promise.all([
  writeFile(new URL('../src/data/cosmicFlowGroups.ts', import.meta.url), generatedGroups),
  writeFile(new URL('../src/data/cosmicFlowMetadata.ts', import.meta.url), generatedMetadata),
]);
console.log(JSON.stringify({
  sourceSha256,
  sourceRows: rows.length,
  sliceRows: slice.length,
  selectedRows: selected.length,
  packedBytes: packed.length,
}, null, 2));
