// Generated by scripts/updateCosmicFlowCatalog.mjs.
export const CF4_GROUP_SOURCE_URL = 'https://cdsarc.cds.unistra.fr/ftp/J/ApJ/944/94/table4.dat.gz';
export const CF4_GROUP_SOURCE_SHA256 = 'be91d4fae6fa01552ab3bc85db695411fca3249eeae08b566a712e6ea790bd99';
export const CF4_GROUP_SOURCE_ROW_COUNT = 38053;
export const CF4_GROUP_SLICE_AVAILABLE_COUNT = 3800;
export const CF4_GROUP_SAMPLE_COUNT = 1900;
export const CF4_GROUP_SLICE_SGZ_LIMIT_VELOCITY_UNITS = 1000;
